New components
chingu-voyages/v41-bears-team-29 pull request #18
Opened 2022-10-27 14:06 UTC by letsbehuman

I have created newUserBtn, goBackBtn, cameraBtn and modify CardComponent :D

2022-10-27 15:43 UTC, 7-Dany requested changes

2022-10-27 15:43 UTC, 7-Dany commented on Front-end/components/goBackbtn.js
> +import { Ionicons } from "@expo/vector-icons";
@expo/vector-icons is not installed

2022-10-27 15:43 UTC, 7-Dany commented on Front-end/screens/CaptureScreen.js
> +import GoBackBtn from "../components/goBackBtn";
goBackBtn it should be goBackbtn

2022-10-27 15:43 UTC, 7-Dany commented on Front-end/screens/ScoreScreen.js
> +import GoBackBtn from "../components/goBackBtn";
goBackBtn should be goBackbtn

2022-10-27 15:43 UTC, 7-Dany commented on Front-end/screens/ProfileAdmin.js
> +          <Card />
Using card component without passing item props

2022-10-27 15:43 UTC, 7-Dany commented on Front-end/screens/ProfileAdmin.js
> +              <Card user={item} deleteUserHandler={deleteUserHandler} />
There is no user and deleteUserHandler in Card props

2022-10-28 12:04 UTC, letsbehuman commented on Front-end/screens/CaptureScreen.js
> +import GoBackBtn from "../components/goBackBtn";
I changed the component name so everything will be ...Btn

2022-10-28 17:34 UTC, merged